services:
  - type: web
    name: heroesdelplaneta
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi:application"
    plan: free
    build:
      environment:
        pythonVersion: 3.11.9
buildCommand: "pip install -r requirements.txt"
startCommand: "gunicorn config.wsgi:application"
preDeployCommand: "python manage.py collectstatic --noinput"
