services:
  - type: web
    name: heroesdelplaneta
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
